foods = {'oil': 'baking', 
         'chocolate': 'baking', 
         'cornstarch': 'baking', 
         'sugar': 'baking',
         'flour': 'baking',
         'shortening': 'baking',
         'vanilla': 'baking',

         'water': 'beverages',
         'wine': 'beverages', 
         'soda': 'beverages',
         'ice': 'beverages',

         'mayonnaise': 'condiments', 
         'ketchup': 'condiments', 
         'sauce': 'condiments',
         'mustard': 'condiments', 

         'egg': 'dairy',
         'butter': 'dairy', 
         'cheese': 'dairy', 
         'milk': 'dairy',

         'salmon': 'fish', 
         'tuna': 'fish',

         'bread': 'grains',
         'pasta': 'grains', 
         'cracker': 'grains', 
         'oat': 'grains',
         'rice': 'grains',

         'broth': 'grocery', 
         'syrup': 'grocery',

         'steak': 'meat', 
         'beef': 'meat', 
         'chicken': 'meat',

         'seed': 'nuts', 
         'nut': 'nuts', 
         'almond': 'nuts',

         'tomato': 'produce',
         'tomatoes': 'produce',
         'lemon': 'produce', 
         'banana': 'produce', 
         'apple': 'produce', 
         'onion': 'produce', 
         'potato': 'produce', 
         'potatoes': 'produce',
         'carrot': 'produce',
         'lime': 'produce',
         'cauliflower': 'produce',
         'cabbage': 'produce',
         'cucumber': 'produce',
         'orange': 'produce',

         'garlic': 'spices',
         'salt': 'spices', 
         'pepper': 'spices', 
         'basil': 'spices', 
         'ginger': 'spices',
         'paprika': 'spices',
         'thyme': 'spices',
         'allspice': 'spices',
         'cumin': 'spices'
}
